name = "CurveIntersect"
uuid = "bd516f89-2b5c-4db0-9d68-921a63cc5ead"
authors = ["Thomas Marks <marksta@umich.edu>"]
version = "0.1.0"

[deps]

[extras]
Contour = "d38c429a-6771-53c6-b99e-75d170b6e991"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Contour", "Plots"]
